### ISSUE TITLE
Unknown entity???

### ISSUE THREAD

**Issue by CoreNovaPlays** [YanisBft/Mooblooms#10]
Hey there!

I installed the mod on both my server and client. Both of them have config files. But when I tried to /summon mooblooms:[any of them] I get the "unknown entity" error. Am I doing something wrong?

Thank you!

**Comment by YanisBft** [comment]
Hey! What other mods do you have?
Can you provide the latest.log file when you execute the command please?

**Comment by CoreNovaPlays** [comment]
Hey there!

It's so weird. So I re-installed the mod to my server to test it again. And
now it works. I haven't changed anything though. Here's a list of my mods
though in case it helps:

**Origins:**
1) Origins - https://www.curseforge.com/minecraft/mc-mods/origins [has 1.17]
2) Extra Origins -
https://www.curseforge.com/minecraft/mc-mods/extra-origins [has 1.17]
3) Mob Origins - https://www.curseforge.com/minecraft/mc-mods/mob-origins
[has 1.17]
4) Expanded Origins (aka Origins+) -
https://www.curseforge.com/minecraft/mc-mods/origins-plus
5) Pehkui - https://www.curseforge.com/minecraft/mc-mods/pehkui
6) Mermod Fabric -
https://www.curseforge.com/minecraft/mc-mods/mermod-fabric

**World Manipulators:**
1) Better Caves -
https://www.curseforge.com/minecraft/mc-mods/yungs-better-caves-fabric
2) Cave Biomes - https://www.curseforge.com/minecraft/mc-mods/cave-biomes
[has 1.17]
3) Better Nether - https://www.curseforge.com/minecraft/mc-mods/betternether
[has 1.17]
4) Better End - https://www.curseforge.com/minecraft/mc-mods/betterend [has
1.17]
5) Oh the Biomes You'll Go -
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric
6) MoStructures - https://www.curseforge.com/minecraft/mc-mods/mo-structures
[has 1.17]
7) Repurposed Structures -
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric
[has 1.17]
8) Draylar's Battle Towers -
https://www.curseforge.com/minecraft/mc-mods/draylars-battle-towers
9) Biome Makeover -
https://www.curseforge.com/minecraft/mc-mods/biome-makeover
10) Better Mineshaft -
https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-fabric
11) Desolation - https://www.curseforge.com/minecraft/mc-mods/desolation
12) Wild World - https://www.curseforge.com/minecraft/mc-mods/wild-world
13) Endless Oceans: Adventures:
https://www.curseforge.com/minecraft/mc-mods/endless-oceans-adventures-fabric

**Mobs:**
1) Gentle Fawn - https://www.curseforge.com/minecraft/mc-mods/gentle-fawn
2) Direbats - https://www.curseforge.com/minecraft/mc-mods/direbats-fabric
3) Monster of the Ocean Depths -
https://www.curseforge.com/minecraft/mc-mods/monster-of-the-ocean-depths-fabric
4) Rat's Mischief -
https://www.curseforge.com/minecraft/mc-mods/rats-mischief [has 1.17]
5) Duck Mod -
https://www.curseforge.com/minecraft/mc-mods/untitled-duck-mod-fabric [has
1.17]
6) RPG Difficulty -
https://www.curseforge.com/minecraft/mc-mods/rpgdifficulty [has 1.17]
7) Crimson Moon - https://www.curseforge.com/minecraft/mc-mods/crimson-moon
8) Eldritch Mobs -
https://www.curseforge.com/minecraft/mc-mods/eldritch-mobs [has 1.17]
9) MobZ - https://www.curseforge.com/minecraft/mc-mods/mobz
10) Terrarian Slimes -
https://www.curseforge.com/minecraft/mc-mods/terrarian-slimes/files/3358232
[has 1.17]
11) El Huevo - https://www.curseforge.com/minecraft/mc-mods/el-huevo-fabric
12) Grizzly Bear - https://www.curseforge.com/minecraft/mc-mods/grizzly-bear
[has 1.17]

**QOL:**
1) Vanilla Death Chest -
https://www.curseforge.com/minecraft/mc-mods/vanilladeathchest-fabric
2) Villager Names -
https://www.curseforge.com/minecraft/mc-mods/villager-names-fabric [has
1.17]
3) NPC Variety -
https://www.curseforge.com/minecraft/mc-mods/npc-variety-port [has 1.17]
4) Dual Riders - https://www.curseforge.com/minecraft/mc-mods/dual-riders
[has 1.17]
5) Damage Tilt - https://www.curseforge.com/minecraft/mc-mods/damage-tilt
[has 1.17]
6) Curios - https://www.curseforge.com/minecraft/mc-mods/curios-fabric
7) Adorn - https://www.curseforge.com/minecraft/mc-mods/adorn [has 1.17]
8) Carrier - https://www.curseforge.com/minecraft/mc-mods/carrier [has 1.17]
9) Environmental Armor -
https://www.curseforge.com/minecraft/mc-mods/environmental-armor [has 1.17]
10) Secret Rooms -
https://www.curseforge.com/minecraft/mc-mods/secret-rooms-fabric [has 1.17]
11) Color Unchained -
https://www.curseforge.com/minecraft/mc-mods/color-unchained
12) Iron Jetpacks -
https://www.curseforge.com/minecraft/mc-mods/iron-jetpacks-fabric
13) Hookshot - https://www.curseforge.com/minecraft/mc-mods/hookshot [has
1.17]
14) Auto Switch -
https://www.curseforge.com/minecraft/mc-mods/fabric-autoswitch [has 1.17]

*MISC:**
1) Fabric API - https://www.curseforge.com/minecraft/mc-mods/fabric-api
[has 1.17]
2) Yung's API -
https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric [has 1.17]
3) Fabric Kotlin -
https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin [has
1.17]
4) GeckoLib - https://www.curseforge.com/minecraft/mc-mods/geckolib
5) Cloth Config API -
https://www.curseforge.com/minecraft/mc-mods/cloth-config [has 1.17]
6) Mod Menu - https://www.curseforge.com/minecraft/mc-mods/modmenu [has
1.17]
7) Cloth API - https://www.curseforge.com/minecraft/mc-mods/cloth-api [has
1.17]
8) OptiFabric - https://www.curseforge.com/minecraft/mc-mods/optifabric
[has 1.17]
9) OptiFine - https://optifine.net/downloads

(Total: 54 Mods)

**Comment by YanisBft** [comment]
I'll close this issue for now, which never happened to me. If you have this issue again, please reopen
