### ISSUE TITLE
1.19.1 Support - (Download Linked)

### ISSUE THREAD

**Issue by PremiereSetups** [YanisBft/Mooblooms#17]
Hey guys, I figured this is the best place to put it, but I had a developer update the mod to 1.19 and 1.19.1 fabric, you can find the source and .jar below.

File:
https://mega.nz/file/YRZkTASY#pO7mtNjSHmAUK4lyQPcG6AZuexWj9kOT0Tk1wBqBCgM

Source: 
[mooblooms-main.zip](https://github.com/YanisBft/Mooblooms/files/9305101/mooblooms-main.zip)

**Comment by jadelily18** [comment]
***highly*** suggest moving this to GitHub releases
