### ISSUE TITLE
Crash with BetterNether or status effect

### ISSUE THREAD

**Issue by TimelapsedEon** [YanisBft/Mooblooms#7]
[2020-09-13-2.log.gz](https://github.com/YanisBft/Mooblooms/files/5214571/2020-09-13-2.log.gz)
I created a cluckshroom spawner in the nether and have BetterNether installed. The cluckshrooms were fine until they encountered an egg plant, giving it poison, where upon this crash report. After regenerating the nether without egg plants, I got a similar error about collision with minecraft:air.

Any thoughts? Version 1.3.0 of your mod, 1.16.1 of minecraft.

**Comment by YanisBft** [comment]
Indeed, it's only due to my bad code. Will release a patch soon
