### ISSUE TITLE
Mobs not naturally spawning. (might be my fault so Im sorry if it this is the case)

### ISSUE THREAD

**Issue by Silver0793** [YanisBft/Mooblooms#8]
Hello I am running the latest 1.16.4 version of this mod as I type this which is 1.4.0. I have added this mod into an existing world however I cannot seem to come across any of these mooblooms, I am on a server and my friend who lives in the nether seems to have the same issues even though the nether was generated after the mod had been added. My question is would I need to load in new chunks for the mobs to spawn as it is an existing world? 
The current modlist is like as so, I am including it in case that one of these mods are causing the issue.
![image](https://user-images.githubusercontent.com/80760246/111307211-05a36780-8651-11eb-99d4-5326b45fae6b.png)

**Comment by YanisBft** [comment]
Version 1.5.1 with https://github.com/YanisBft/Mooblooms/commit/8a4df5419be37916876778ed8844d5c8cab53cab should have helped fixing this issue
