### ISSUE TITLE
Adults and their baby counterparts have the same full sized hitbox

### ISSUE THREAD

**Issue by Omegapex** [YanisBft/Mooblooms#9]
As the title says, the baby animals all have adult hitboxes rather than smaller ones to reflect their stature like all vanilla ones do. This makes it impossible to sort them out through any means.
![image](https://user-images.githubusercontent.com/20981411/123489755-aacec400-d5e0-11eb-8c79-145f4481f5fa.png)

**Comment by YanisBft** [comment]
Oops, never noticed that, sorry! Will be fixed in the next update
